// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5Io-iAz2oTPCiRWz9pnF5vq6s6a8JGM',
    appId: '1:235717104176:web:6fc8e40171b7b0f44713f5',
    messagingSenderId: '235717104176',
    projectId: 'test-postgrace',
    authDomain: 'test-postgrace.firebaseapp.com',
    storageBucket: 'test-postgrace.firebasestorage.app',
    measurementId: 'G-MVMMF8L1XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUULQGxpOOEKRoq7I6MoqRVHDSoYBQTt4',
    appId: '1:235717104176:android:422be71c704f16194713f5',
    messagingSenderId: '235717104176',
    projectId: 'test-postgrace',
    storageBucket: 'test-postgrace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9-18HvKBh6DEcaddjC5Ty6z7H_J-gJk',
    appId: '1:235717104176:ios:5c5a2640f96952c34713f5',
    messagingSenderId: '235717104176',
    projectId: 'test-postgrace',
    storageBucket: 'test-postgrace.firebasestorage.app',
    iosClientId: '235717104176-p4jletph7n1kdna2niihc7d5ubt0l80v.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceKioskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9-18HvKBh6DEcaddjC5Ty6z7H_J-gJk',
    appId: '1:235717104176:ios:5c5a2640f96952c34713f5',
    messagingSenderId: '235717104176',
    projectId: 'test-postgrace',
    storageBucket: 'test-postgrace.firebasestorage.app',
    iosClientId: '235717104176-p4jletph7n1kdna2niihc7d5ubt0l80v.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceKioskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw5Io-iAz2oTPCiRWz9pnF5vq6s6a8JGM',
    appId: '1:235717104176:web:2d5eaf8ceaedbda24713f5',
    messagingSenderId: '235717104176',
    projectId: 'test-postgrace',
    authDomain: 'test-postgrace.firebaseapp.com',
    storageBucket: 'test-postgrace.firebasestorage.app',
    measurementId: 'G-H231MX5PDZ',
  );
}
